# https://travis-ci.org/christoph2/pyA2l
language: python
sudo: required
python:
    - 2.7.8
    - 2.7
    - 3.2
    - 3.3
    - "pypy"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  python -m unittest discover ./pya2l/tests/
